### ISSUE TITLE
Odd behaviour with some Radios

### ISSUE THREAD

**Issue by zkvsky** [mavit/slimpris2#20]
Some streaming radios [Radio Paradise being one] are interactive and allow you to skip ahead and provide per track length. 
Slimmpris displays them as continuous stream with next button disabled, but, when there's something else in queue after [like another radio stream], suddenly the next functionality [it will skip tracks within stream] works and proper track lengths are displayed.

Would it be possible to fix so it works when there's only radio stream in queue?

**Comment by mavit** [comment]
Thanks for the report!  This is fixed in version 3.0.4.

**Comment by zkvsky** [comment]
> Thanks for the report! This is fixed in version 3.0.4.

Thank you!
Now, the problem is that you cannot use skip to go to next track :D but solving that would require implementation of playlist control on both sides.. I don't know if there MPRIS controler with such functionality even...
