### ISSUE TITLE
Remote end closed connection without response

### ISSUE THREAD

**Issue by eater** [mavit/slimpris2#3]
Trying to connect to a server on my local network and this is what I get:

```
2019-03-19 14:11:07,489 slimpris2 WARNING: By not supplying a path for the music library this program will break the MPRIS specification!
2019-03-19 14:11:07,527 slimpris2 ERROR: Could not connect to LMS: Remote end closed connection without response
2019-03-19 14:11:08,561 slimpris2 ERROR: Could not connect to LMS: Remote end closed connection without response
2019-03-19 14:11:09,565 slimpris2 ERROR: Could not connect to LMS: Remote end closed connection without response
2019-03-19 14:11:10,565 slimpris2 ERROR: Could not connect to LMS: Remote end closed connection without response
2019-03-19 14:11:11,569 slimpris2 ERROR: Could not connect to LMS: Remote end closed connection without response
2019-03-19 14:11:12,569 slimpris2 INFO: Continue to connect but going silent
```

**Comment by eater** [comment]
```
# Copy this to /etc/slimpris2.conf or ~/.config/slimpris2/slimpris2.conf
# Default values are shown here, commented out.

[Connection]
host = 192.168.50.106
port = 9002
mac = 00-04-20-12-46-86
#password = 
music_dir = "/volume1/Music"

[Bling]
mmkeys = False
notify = False

```

**Comment by eater** [comment]
Oh and the server log says:

`[19-03-19 14:11:11.8145] Slim::Web::JSONRPC::requestMethod (487) 00-04-20-12-46-86: request not dispatchable!`

**Comment by mavit** [comment]
In the example `slimpris2.conf`, `mac` is colon-separated, not hyphen-separated.  Does changing all of the `-` for `:` help?

**Comment by eater** [comment]
No, when I tried that yesterday, it changed the log message's punctuation but it didn't work any better. I also tried setting a blank `mac = ` and I get the same slimpris2 output, and the log said
`Slim::Web::JSONRPC::requestMethod (487) request not dispatchable!`

Here's a log from this morning with the correct colonized MAC and Debug mode set on JSON-RPC logging: http://paste.ubuntu.com/p/8FR8xq6PVx/

**Comment by mavit** [comment]
What version of Logitech Media Server?  Has this ever worked for you?  Has anything changed recently?

**Comment by mavit** [comment]
If you `telnet` to port 9090 of your Logitech Media Server, does the command `00:04:20:12:46:86 status 0 - tags:` seem to work?

**Comment by eater** [comment]
Logitech Media Server Version: 7.9.2 - 0010.1524841547 running on a Synology box. I've never tried slimpris2 before yesterday. That telnet command just hangs till I quit the terminal window. 

BUT that made me think to try the player name, and that works. Both via telnet and in the conf file, `mac = bedroom`.

**Comment by mavit** [comment]
That version of Logitech Media Server looks like a nightly developer snapshot from nearly a year ago.  Please re-test with a recent build, and, if you still have problems, report it at https://github.com/Logitech/slimserver/issues.  Thanks.

**Comment by eater** [comment]
That's the most recent build that's packaged for Synology, and I don't have a dev toolchain available to build my own for that machine. Works fine as long as I use the player name instead of the MAC.
