### ISSUE TITLE
configure fails with a syntax error in the script

### ISSUE THREAD

**Issue by xxxserxxx** [mavit/slimpris2#4]
```
checking for a Python interpreter with version >= 3.6... python
checking for python... /usr/bin/python
checking for python version... 3.9
checking for python platform... linux
checking for python script directory... ${prefix}/lib/python3.9/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python3.9/site-packages
./configure: line 2622: syntax error near unexpected token `0.26'
./configure: line 2622: `IT_PROG_INTLTOOL(0.26)'
```

It is entirely possible I'm missing a dependency; are the dependencies listed anywhere?

OS: Linux 5.9.13-arch1-1  
Python: 3.9.0  
slimpris2: From git master, rev 6a74199, Tue Sep 29 09:46:01 2020

**Comment by xxxserxxx** [comment]
Ok, the project has a dependency on `intltool`.

Edit: and:

- simplejson (Arch: python-simplejson)
- notify (if you want Notify = true; Arch: python-notify)
- libnotify

However, even with notify, it doesn't work for me; the code throws a "Notify has no attribute init".  Disabling notifications allows it to run, but it refuses to connect to the server, complaining:

```
2020-12-12 14:05:57,501 slimpris2 ERROR: Could not connect to LMS: Remote end closed connection without response
```

This, however, is probably a completely different issue and I'll file a different ticket.

**Comment by mavit** [comment]
> It is entirely possible I'm missing a dependency; are the dependencies listed anywhere?

The best place to look is probably the RPM .spec file.  These are for Fedora, but they give you an idea.

```console
$ grep Requires slimpris2.spec
BuildRequires:          autoconf
BuildRequires:          automake
BuildRequires:          intltool
BuildRequires:          python3-devel
BuildRequires:          systemd
BuildRequires:          systemd-rpm-macros
Requires:               python3dist(dbus-python)
Requires:               python3dist(pygobject)
Requires:               python3dist(simplejson)
Requires:               python3dist(six)
```

Using automake with Python is pretty unusual, I think.

> However, even with notify, it doesn't work for me; the code throws a "Notify has no attribute init".

I don't use the notification feature, and I don't think I've touched it since I took over maintenance.  If you're interested in using it, I expect it'll need some work.

**Comment by xxxserxxx** [comment]
Ok, thanks.  I'd look into it, but the Arch documentation example for python-notify uses the same syntax (including the `init` call), which makes me think this has to do with something more esoteric than an API change, so it's probably something outside of what I can track down.  Anyway, I only noticed because notifications default to enabled, so unless it is explicitly turned off in the config `slimpris2` throws those errors on start-up.
