### ISSUE TITLE
Date parsing error

### ISSUE THREAD

**Issue by xxxserxxx** [mavit/slimpris2#7]
Is there a way to configure the date format in slimpris2?  I have my dates set to ISO 8601 format, and it seems this is confusing slimpris2.  That's my guess, anyway:

```
2020-12-13 19:07:21,991 slimpris2 WARNING: Could not parse addedTime: time data '2020-12-13 Sunday, 19:02' does not match format '%A, %d %B %Y, %H:%M'
```

LMS isn't reporting a strictly conforming ISO format, but slimpris2 is expecting something completely different.  This, I think I can probably track down and address in the Python code but I'd like to first know whether it's a configurable option so I don't have to tweak the source.

**Comment by xxxserxxx** [comment]
1. This was a warning, not an error. My bad.  slimpris2 appears to ignore this issue.
2. The hack was to fix the format in the slimpris2 executable, with something like:
```
sudo sed -i 's/%A, %d %B %Y, %H:%M/%Y-%m-%d %A, %H:%M/' $(which slimpris2)
```
3. A better fix would be to make the change in `slimpris2.in`
4. The best fix would to make this format configurable, rather than hard-coded
5. The betterestest would add a whole bunch of error-prone logic to try to intelligently guess at the date format based on what's returned -- there are, after all, a fixed number of ways it can be configured in the LMS GUI, reducing the number of options to a handful.

I eliminated the warning enough to close.

**Comment by mavit** [comment]
Thanks for the report.

Option 6, the most bestest, would be to query LMS to ask it what date format it's using.  However, I've gone for option 7, which is to simply drop this code -- it's only used to report what time a track was added to LMS's database, which probably isn't terribly important to know.

**Comment by xxxserxxx** [comment]
Ooo, well, yeah. If LMS supports that, then 6 is obviously the most bestest.  However, if it can be eliminated, that's swell, too.

Thanks again.  slimpris2 is now working well.  Thanks for keeping the project alive.
